id: PB68756AB
initial_creation_type: input
source_metadata:
  Title: Nyāyapraveśaka Sūtram
  Editor: Dhruva, A.B.
  Publisher: Sri Satguru Publications
  Place of Publication: Delhi, India
  Year: '1987'
  Nyāyapraveśakasūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:12:17.506272'
last_modified_at: '2022-03-08T16:12:17.506280'
